services:
  backend:
    image: kachabazar-backend:1.0
    container_name: kachabazar-backend
    env_file:
      - ./backend/.env
    ports:
      - "5055:5055"
    restart: unless-stopped

  seed:
    image: node:20-bookworm-slim
    working_dir: /app
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: sh -c "npm ci && npm run data:import"
    restart: "no"

  store:
    image: kachabazar-store:1.0
    container_name: kachabazar-store
    env_file:
      - ./store/.env
    ports:
      - "3000:3000"
    restart: unless-stopped

  admin:
    image: kachabazar-admin:1.1
    container_name: kachabazar-admin
    ports:
      - "4100:80"
    restart: unless-stopped

# services:
#   backend:
#     image: kachabazar-backend:1.0
#     container_name: kachabazar-backend
#     env_file:
#       - ./backend/.env
#     ports:
#       - "5055:5055"
#     restart: unless-stopped

#   seed:
#     image: node:20-bookworm-slim
#     working_dir: /app
#     volumes:
#       - ./backend:/app
#     env_file:
#       - ./backend/.env
#     command: sh -c "npm ci && npm run data:import"
#     restart: on-failure:3

#   store:
#     image: kachabazar-store:1.0
#     container_name: kachabazar-store
#     ports:
#       - "3000:3000"
#     restart: unless-stopped

#   admin:
#     image: kachabazar-admin:1.0
#     container_name: kachabazar-admin
#     ports:
#       - "4100:80"
#     restart: unless-stopped

# services:
#   mongodb:
#     image: mongo:7
#     container_name: kachabazar-mongodb
#     volumes:
#       - mongodb_data:/data/db
#     restart: unless-stopped

#   backend:
#     image: kachabazar-backend:1.0
#     container_name: kachabazar-backend
#     env_file:
#       - ./backend/.env
#     environment:
#       MONGO_URI: mongodb://mongodb:27017/kachabazar
#       PORT: 5055
#     ports:
#       - "5055:5055"
#     depends_on:
#       - mongodb
#     restart: unless-stopped

#   store:
#     image: kachabazar-store:1.0
#     container_name: kachabazar-store
#     ports:
#       - "3000:3000"
#     restart: unless-stopped

#   admin:
#     image: kachabazar-admin:1.0
#     container_name: kachabazar-admin
#     ports:
#       - "4100:80"
#     restart: unless-stopped

# volumes:
#   mongodb_data:
