services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: kachabazar-backend:1.0
    container_name: kachabazar-backend
    env_file:
      - ./backend/.env
    ports:
      - "5055:5055"
    restart: unless-stopped

  seed:
    image: node:20-bookworm-slim
    working_dir: /app
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: sh -c "npm ci && npm run data:import"
    restart: "no"

  store:
    build:
      context: ./store
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://host.docker.internal:5055/api
    image: kachabazar-store:1.0
    container_name: kachabazar-store
    env_file:
      - ./store/.env
    ports:
      - "3000:3000"
    restart: unless-stopped

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
      args:
        VITE_APP_API_BASE_URL: http://localhost:5055/api
        VITE_APP_ENCRYPT_PASSWORD: ${VITE_APP_ENCRYPT_PASSWORD}
    image: kachabazar-admin:1.1
    container_name: kachabazar-admin
    env_file:
      - ./admin/.env
    ports:
      - "4100:80"
    restart: unless-stopped
