services:
  backend:
    image: kachabazar-backend:1.0
    container_name: kachabazar-backend
    env_file:
      - ./backend/.env
    ports:
      - "5055:5055"
    restart: unless-stopped

  seed:
    image: node:20-bookworm-slim
    working_dir: /app
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: sh -c "npm ci && npm run data:import"
    restart: "no"

  store:
    image: kachabazar-store:1.0
    container_name: kachabazar-store
    env_file:
      - ./store/.env
    ports:
      - "3000:3000"
    restart: unless-stopped

  admin:
    image: kachabazar-admin:1.1
    container_name: kachabazar-admin
    ports:
      - "4100:80"
    restart: unless-stopped
